[package]
name = "MultiTimerTUI"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.19.0"
crossterm = "0.25"
bitflags = "1.3"
cassowary = "0.3"
unicode-segmentation = "1.2"
unicode-width = "0.1"
termion = { version = "2.0.1", optional = true }
serde = { version = "1", optional = true, features = ["derive"]}
rand = "0.8"
chrono = "0.4.23"
